In [5]:
import requests
import json
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO
import time
import random

In [6]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

In [7]:
resp = requests.get('https://www.fantasypros.com/nfl/stats/qb.php?year=2025&range=full', headers= headers)
soup = BeautifulSoup(resp.text, "html.parser")
soup = soup.find("table")

In [8]:
df = pd.read_html(StringIO(resp.text))

In [9]:
df = df[0]
df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0 PASSING                       \
                Rank                   Player     CMP  ATT   PCT  YDS  Y/A
0                  1         Josh Allen (BUF)      85  121  70.2  964  8.0
1                  2      Lamar Jackson (BAL)      68   95  71.6  869  9.1
2                  3  Patrick Mahomes II (KC)      87  142  61.3  939  6.6
3                  4          Drake Maye (NE)      91  123  74.0  988  8.0
4                  5        Jalen Hurts (PHI)      70  101  69.3  609  6.0

                RUSHING         MISC
   TD INT SACKS     ATT  YDS TD   FL  G  FPTS FPTS/G   ROST
0   7   1     7      31  159  3    0  4  99.5   24.9  99.8%
1  10   1    15      21  166  1    1  4  94.4   23.6  99.8%
2   7   1     7      22  130  2    0  4  89.6   22.4  98.9%
3   7   2    13      24   98  2    1  4  85.5   21.4  82.9%
4   5   0     9      41  179  4    1  4  84.2   21.1  99.7%

In [10]:
fantasy_pros_base = 'https://www.fantasypros.com/nfl/stats/'

positions = {'qb': 'qb.php?',
             'rb': 'rb.php?',
             'wr': 'wr.php?',
             'te': 'te.php?',
             'k': 'k.php?',
             'dst': 'dst.php?',
             'dl': 'dl.php?',
             'lb': 'lb.php?',
             'db': 'db.php?',}

fantasy_range = 'year=2025&rrange=week&week=1'

In [11]:
resp = requests.get(fantasy_pros_base + positions['rb'] + fantasy_range, headers=headers)
resp

In [12]:
df = pd.read_html(StringIO(resp.text))[0]

In [13]:
df.head()

  Unnamed: 0_level_0        Unnamed: 1_level_0 RUSHING                       \
                Rank                    Player     ATT  YDS  Y/A  LG 20+ TD
0                  1      James Cook III (BUF)      75  401  5.3  44   2  5
1                  2     Jonathan Taylor (IND)      77  414  5.4  68   2  3
2                  3      Bijan Robinson (ATL)      64  314  4.9  25   1  1
3                  4  Christian McCaffrey (SF)      69  225  3.3  15   0  0
4                  5          Josh Jacobs (GB)      80  266  3.3  19   0  4

  RECEIVING                   MISC
        TGT REC  YDS   Y/R TD   FL  G  FPTS FPTS/G   ROST
0        13  12   89   7.4  0    0  4  79.0   19.8  99.4%
1        14  13  113   8.7  1    0  4  76.7   19.2  99.6%
2        23  18  270  15.0  1    0  4  70.4   17.6  99.8%
3        43  31  305   9.8  2    0  4  65.0   16.3  99.8%
4        14  10  119  11.9  0    0  4  62.5   15.6  99.7%

In [14]:

roster_positions = [
    'QB', # Quarterback
    'RB', # Runningback
    'RB',
    'WR', # Wide reciever
    'WR',
    'WR',
    'TE', # Tightend
    'FLEX', # Flex
    'FLEX',
    'BN', # Bench
    'BN',
    'BN',
    'BN',
    'BN',
    'BN']

In [15]:
for position in positions:
    resp = requests.get(fantasy_pros_base + positions[position] + fantasy_range, headers=headers)
    df = pd.read_html(StringIO(resp.text))[0]
    df.to_csv(f'week_1/{position}, Week_1')
    time.sleep(random.uniform(1,4))