In [1]:
import requests
import json
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

In [3]:
resp = requests.get('https://www.fantasypros.com/nfl/stats/qb.php?year=2024&range=full', headers= headers)
soup = BeautifulSoup(resp.text, "html.parser")
soup = soup.find("table")

In [4]:
df = pd.read_html(StringIO(resp.text))

In [5]:
df = df[0]
df.head()

  Unnamed: 0_level_0    Unnamed: 1_level_0 PASSING                            \
                Rank                Player     CMP  ATT   PCT   YDS  Y/A  TD
0                  1   Lamar Jackson (BAL)     316  474  66.7  4172  8.8  41
1                  2      Josh Allen (BUF)     307  483  63.6  3731  7.7  28
2                  3      Joe Burrow (CIN)     460  652  70.6  4918  7.5  43
3                  4   Baker Mayfield (TB)     407  570  71.4  4500  7.9  41
4                  5  Jayden Daniels (WAS)     331  480  69.0  3568  7.4  25

            RUSHING          MISC
  INT SACKS     ATT  YDS  TD   FL   G   FPTS FPTS/G   ROST
0   4    23     139  915   4    5  17  434.4   25.6  99.8%
1   6    14     102  531  12    2  17  385.1   22.7  99.7%
2   9    48      42  201   2    5  17  381.9   22.5  97.4%
3  16    40      60  378   3    2  17  381.8   22.5  97.2%
4   9    47     148  891   6    0  17  364.7   21.5  99.7%

In [ ]:
fantasy_pros_base = 'https://www.fantasypros.com/nfl/stats/'

positions = {'qb': 'qb.php?',
             'rb': 'rb.php?',
             'wr': 'wr.php?',
             'te': 'te.php?',
             'k': 'k.php?',
             'dst': 'dst.php?',
             'dl': 'dl.php?',
             'lb': 'lb.php?',
             'db': 'db.php?',}

fantasy_range_full = 'year=2024&range=full'

In [ ]:
resp = requests.get(fantasy_pros_base + positions['rb'] + fantasy_range_full, headers=headers)
resp

In [9]:
df = pd.read_html(StringIO(resp.text))[0]

In [10]:
df.head()

  Unnamed: 0_level_0    Unnamed: 1_level_0 RUSHING                         \
                Rank                Player     ATT   YDS  Y/A  LG 20+  TD
0                  1  Saquon Barkley (PHI)     345  2005  5.8  72  17  13
1                  2   Derrick Henry (BAL)     325  1921  5.9  87  19  16
2                  3    Jahmyr Gibbs (DET)     250  1412  5.6  70  13  16
3                  4  Bijan Robinson (ATL)     304  1456  4.8  37   5  14
4                  5      Josh Jacobs (GB)     301  1329  4.4  38   7  15

  RECEIVING                   MISC
        REC TGT  YDS   Y/R TD   FL   G   FPTS FPTS/G   ROST
0        33  43  278   8.4  2    1  16  322.3   20.1  99.8%
1        19  22  193  10.2  2    1  17  317.4   18.7  99.8%
2        52  63  517   9.9  4    1  17  310.9   18.3  99.8%
3        61  72  431   7.1  1    0  17  280.7   16.5  99.8%
4        36  43  342   9.5  1    3  17  257.1   15.1  99.7%

In [ ]:

roster_positions = [
    'QB', # Quarterback
    'RB', # Runningback
    'RB',
    'WR', # Wide reciever
    'WR',
    'WR',
    'TE', # Tightend
    'FLEX', # Flex
    'FLEX',
    'BN', # Bench
    'BN',
    'BN',
    'BN',
    'BN',
    'BN']